### ISSUE TITLE
develop a tool plot-auroc-profiles to show the evolution of AuROC through generations

### ISSUE THREAD

**Issue by jvanheld** [pvhelden/optimize-matrix-GA#28]
Draw a graph showing the progressive increase of performance scores through generations.

**Comment by jvanheld** [comment]
I have a data table (tsv file) describing the parent-child relationships between nodes of a tree, with some score associated to each node. 

```
generation	AC	AuROC	parent_AC
0	cluster_4	0.7131325493149497	Origin
0	cluster_1_node_1_2motifs	0.6705830895345133	Origin
0	cluster_1_node_2_3motifs	0.6651042783072153	Origin
0	cluster_1_node_3_4motifs	0.6636811690756885	Origin
0	cluster_1	0.6585140341221795	Origin
0	cluster_1_node_5_6motifs	0.6563690872751498	Origin
0	cluster_1_node_8_9motifs	0.6562992787417085	Origin
0	cluster_1_node_9_10motifs	0.6555189294093795	Origin
0	cluster_1_node_6_7motifs	0.6554401413550388	Origin
0	cluster_1_node_4_2motifs	0.6455893172667494	Origin
0	cluster_1_node_7_2motifs	0.6384673985458966	Origin
0	cluster_3	0.5570978767778002	Origin
0	cluster_2	0.5323742142919212	Origin
1	cluster_4_G1_M3_C1	0.723705211018741	cluster_4
1	cluster_4_G1_M3_C3	0.7133906381253079	cluster_4
1	cluster_4	0.7131325493149497	Origin
1	cluster_4_G1_M3_C4	0.7105106740433911	cluster_4
1	cluster_4_G1_M3_C5	0.7104110303276076	cluster_4
1	cluster_4_G1_M3_C2	0.7052166671494369	cluster_4
1	cluster_1_node_1_2motifs_G1_M1_C1	0.6785706630362368	cluster_1_node_1_2motifs
1	cluster_1_node_2_3motifs_G1_M2_C4	0.6712619123482895	cluster_1_node_2_3motifs
1	cluster_1_node_1_2motifs	0.6705830895345133	Origin
1	cluster_1_node_1_2motifs_G1_M1_C3	0.6701306375459832	cluster_1_node_1_2motifs
1	cluster_1_node_1_2motifs_G1_M1_C4	0.6668561538684351	cluster_1_node_1_2motifs
1	cluster_1_node_2_3motifs	0.6651042783072153	Origin
1	cluster_1_node_1_2motifs_G1_M1_C2	0.6649387364945106	cluster_1_node_1_2motifs
1	cluster_1_node_1_2motifs_G1_M1_C5	0.6629890218115461	cluster_1_node_1_2motifs
1	cluster_1_node_2_3motifs_G1_M2_C3	0.6623368478985021	cluster_1_node_2_3motifs
1	cluster_1_node_2_3motifs_G1_M2_C5	0.6623200475045617	cluster_1_node_2_3motifs
1	cluster_1_node_2_3motifs_G1_M2_C2	0.6568565883613825	cluster_1_node_2_3motifs
1	cluster_1_node_2_3motifs_G1_M2_C1	0.6388761115777886	cluster_1_node_2_3motifs
2	cluster_4_G2_M2_C3	0.7409120006951887	cluster_4_G1_M3_C1
2	cluster_4_G2_M1_C4	0.736657300929815	cluster_4
2	cluster_4_G2_M2_C1	0.728083741273933	cluster_4_G1_M3_C1
2	cluster_4_G1_M3_C1	0.723705211018741	cluster_4
2	cluster_4_G2_M2_C5	0.723478695362512	cluster_4_G1_M3_C1
2	cluster_4_G2_M3_C3	0.7211797931813572	cluster_4_G1_M3_C3
2	cluster_4_G2_M2_C4	0.7204835906497121	cluster_4_G1_M3_C1
2	cluster_4_G2_M1_C3	0.7195014917591169	cluster_4
2	cluster_4_G2_M3_C4	0.7179615039249195	cluster_4_G1_M3_C3
2	cluster_4_G2_M1_C5	0.7173718969962052	cluster_4
2	cluster_4_G1_M3_C3	0.7133906381253079	cluster_4
2	cluster_4	0.7131325493149497	Origin
2	cluster_4_G2_M2_C2	0.711375894331315	cluster_4_G1_M3_C1
2	cluster_4_G2_M1_C2	0.7066681632534833	cluster_4
2	cluster_4_G2_M3_C5	0.7063451901630793	cluster_4_G1_M3_C3
2	cluster_4_G2_M3_C1	0.6992420994699186	cluster_4_G1_M3_C3
2	cluster_4_G2_M3_C2	0.6913004373895664	cluster_4_G1_M3_C3
2	cluster_4_G2_M1_C1	0.6882227790168871	cluster_4
```

I would like a python code that takes this kind of table as input and draws a graph where each node (row of the table) is represented as a dot with  generation in abscissa (discrete values) , and AuROC score in ordinates. I would like to have lines joining each node to its parent node. 


-

**Comment by jvanheld** [comment]
I sent the previous comment to ChatGPT. 

Result: this first version of the code already draws a graph that follows the instructions. 

<img width="655" alt="image" src="https://github.com/user-attachments/assets/e08a9330-2452-40be-8677-e72f4716cd3f">


However,

- it does not contain the lines joining each node to its parent
- the dots are too large
- the labels are unreadable because there are a lot of labels at the same location
- there is no indication of the axis (bar, legend, scalebar, ...)

Should be improved.

**Comment by jvanheld** [comment]
Second prompting

> The plut is already showing the trends, but there are too many nodes to see the labels, which are strongly overlapping. Can you do the same plot with the following fatures : 
> 
> - no node labels
> - the dot for each node should be very small (1 or 2 dots diameter)
> - add lines between each node (column AC) and the position of its parent node (node parentAC) at the previous generation (not on the same generation)
> - add  X an Y axes with labels indicating the generation (X) and AuROC (Y), respectively

result: 

<img width="561" alt="image" src="https://github.com/user-attachments/assets/171e65f1-04f2-4093-9630-30f7a2c21fc2">

**Comment by jvanheld** [comment]
After iterative prompting (13 prompts) ChatGPT added several options to fine-tune the graph. 

Two examples of results, 

1. with the full set of generations

```
venv/Downloads/bin/python plot-auroc-profiles.py -v 1 -i data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table.tsv -o data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table_plot.pdf -f pdf -t PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices  -s "train versus rand" --y_step1 0.1 --y_step2 0.01 --min_y 0.5 --max_y 1 --xsize 16 --ysize 8
```

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/6b5a793a-59aa-4568-982e-9e01635fa40d">


3. with a zoom on generations 10 to 20

```
venv/Downloads/bin/python plot-auroc-profiles.py -v 1 -i data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table.tsv -o data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table_gen10-20_plot.pdf -f pdf -t PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices  -s "train versus rand" --y_step1 0.1 --y_step2 0.01 --min_g 10 --max_g 20 --min_y 0.8 --max_y 0.904 --xsize 16 --ysize 8
```

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/34565087-d178-42ed-a85c-6e160419d4b1">

**Comment by jvanheld** [comment]
@pvhelden , if you have time I think it would be good to revise the script, clean it and fix some minor bugs. 

I have a bug when I use --min_g and --max_g without --min_y and --max_y. 

```
caminante-4:optimize-matrix-GA $ venv/Downloads/bin/python plot-auroc-profiles.py -v 1 -i data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table.tsv -o data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table_gen10-20_plot.pdf -f pdf -t PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices  -s "train versus rand" --y_step1 0.1 --y_step2 0.01 --min_g 10 --max_g 20 --xsize 16 --ysize 8
Running command: python plot-auroc-profiles.py -i data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table.tsv -o data/score_tables/PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices_train-vs-rand_gen0-20_score_table_gen10-20_plot.pdf -f pdf -t "PRDM5_GHTS_YWK_B_AffSeq_B1_PRDM5.C2_clust-trimmed-matrices" -s "train versus rand"   --min_g 10 --max_g 20 --y_step1 0.1 --y_step2 0.01 --xsize 16.0 --ysize 8.0 --dpi 100
Warning: Node 'cluster_4_G8_M3_C3' is missing from the filtered data.
Warning: Node 'cluster_4_G8_M5_C2' is missing from the filtered data.
Warning: Node 'cluster_4_G8_M1_C4' is missing from the filtered data.
Traceback (most recent call last):
  File "/Users/jvanheld/no_backup/rsat_github/optimize-matrix-GA/plot-auroc-profiles.py", line 167, in <module>
    main()
  File "/Users/jvanheld/no_backup/rsat_github/optimize-matrix-GA/plot-auroc-profiles.py", line 148, in main
    plot_tree(
  File "/Users/jvanheld/no_backup/rsat_github/optimize-matrix-GA/plot-auroc-profiles.py", line 79, in plot_tree
    y_ticks1 = [round(i * y_step1, 1) for i in range(int(min_y // y_step1), int(max_y // y_step1) + 1)]
                                                         ~~~~~~^^~~~~~~~~
TypeError: unsupported operand type(s) for //: 'NoneType' and 'float'


```

**Comment by jvanheld** [comment]
The option --y_min works with the second example above (generations 10 to 20), but not with the first one (all generations).

**Comment by jvanheld** [comment]
@pvhelden 

I asked ChatGPT if it could adapt the code in order to choose dot colors according to the selection status. 

Prompt: 

> Would it be possible to adapt the doc colors according to an additional column "selected" which contains 0 and 1 flags. The nodes dot would be  red ('#FF0000')  for flag 1 and a slightly dark green ('#008800') for flag 1. 
> 
> Also, the nodes flagged 1 should be plotted (or re-plotted) after those flagged 0, in order to highlight the green dots (we have many superimposed dots, and there are fewer selected than non-selected nodes at each generation) 

The new code generated execution errors. I asked ChatGPT to fix them but if failed, I guess at this stage the soft becomes too delicate to evolve by simple prompting of a generative IA.
